# Generated by Django 3.2.5 on 2021-10-28 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.car'),
        ),
        migrations.AlterField(
            model_name='service',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ServiceDescription',
        ),
    ]
